config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  after_initialize :init
  def init
    self.upvoteCount ||= 0.0
    self.poster ||= "Anon"
  end

  validates :title, :content, :presence => true
  validates :title, :length => { :minimum => 2 }
  validates :title, :uniqueness => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
		def index
			@posts = Post.all
		end

		def new
			@post =  Post.new(params[:post].permit(:title,:content))
		end

		def show
			@post = Post.find(params[:id])
		end

		def new

		end

		def create
			@post = Post.new(params[:post].permit(:title, :content, :poster, :upvoteCount))
			if @post.save
				redirect_to posts_path, :notice => "Your Book Submitted for Approval"
			else
				render "new"
			end
		end

		def edit

		end

		def update

		end

		def destroy

		end

		def updateCount
			@post = Post.find(params[:id])
			@post.increment! :upvoteCount
		end
		helper_method :updateCount

		private
		def post_params
			params.require(:post).permit(:title,:content, :poster, :upvoteCount)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/index/new.html.erb
<h1>Add A New Post</h1>

app/views/index/show.html.erb
<small> <%= @post.title %> </small>
<br>
<small> <%= @post.content %> </small>
<br>
<small> <%= @post.poster %> </small>
<br>
<small> <%= @post.created_at%> </small>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BookHunt</title>
  <%=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%=javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
      <%=csrf_meta_tags %>
</head>

<body>
  <%=yield %>
</body>

</html>

app/views/posts/index.html.erb
<title>Book Hunt</title>
<div class="navbar navbar-default">
  <div class="navbar-header">
    <a class="navbar-brand" href="/posts"><div class="numberCircle"><p>BH</p></div></a>
  	<p class = "titleHeader">Book Hunt</p>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
    </li>
    <% if user_signed_in? %>
    <li><div class="btn btn-primary" style="color:#fff;margin-top:20px; margin-right:10px;"><%= link_to(current_user.email, destroy_user_session_path, :method => :delete)   %></div>
    </li>
    <% else %>
      <li><div class="btn btn-primary" style="color:#fff;margin-top:20px; margin-right:10px;"><%= link_to "LOGIN",'/users/sign_in' %></div></li>
    <% end %>
    <li><div class="btn btn-primary" style="color:#fff;margin-top:20px; margin-right:10px;"><%= link_to "SUBMIT BOOK",new_post_path %></div></li>
    </ul>
  </div>
</div>

<div class ="centerTable">

<div class = "title">
  <h4> Today </h4>
</div>

  <div class = "table">
  	<table class="table table-striped table-hover ">
  	  <tbody>
  	    <tr>
  	    <% @posts.each do |post| %>
  	      <td><div class="numberSquare"><div class="arrow-up"></div><p><%= post.upvoteCount %></p></div></td>
  	      <td><%= link_to post.title, post %></td>
  	      <td><%= post.content %></td>
  	      <td><%= post.poster %></td>
  	      </tr>
  	<% end %>
  	  </tbody>
  	</table>
  </div>
</div>

app/views/posts/new.html.erb
<title>Book Hunt</title>
<div class="navbar navbar-default">
  <div class="navbar-header">
    <a class="navbar-brand" href="/posts"><div class="numberCircle"><p>BH</p></div></a>
    <p class = "titleHeader">Book Hunt</p>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
    </li>
    <% if user_signed_in? %>
    <li><div class="btn btn-primary" style="color:#fff;margin-top:20px; margin-right:10px;"><%= link_to(current_user.email, destroy_user_session_path, :method => :delete)   %></div></li>
    <% else %>
      <li><div class="btn btn-primary" style="color:#fff;margin-top:20px; margin-right:10px;"><%= link_to "LOGIN",'/users/sign_in' %></div></li>
    <% end %>
    </ul>
  </div>
</div>
<div class="container">
  <header class="codrops-header">
    <h1>Add a New Book <span>Submit a Book you think is cool</span></h1>
  </header>

  <section>
    <%= form_for Post.new do |f| %>

    <!-- Title -->
    <p>
        <h4 style="color:#fff">Book Title</h4><br />
        <%= f.text_field :title, :size => 100 %>
    </p>

    <!-- Content -->
    <p>
        <h4 style="color:#fff">Brief Description</h4><br />
        <%= f.text_field :content, :size => 100 %>
    </p>

    <!-- Submit -->
    <p>
      <%= f.submit "Add a new Book" %>
    </p>

    <% end %>
  </section>
  <div>
</div>

app/views/posts/show.html.erb
<title>Book Hunt</title>
<div class="navbar navbar-default">
  <div class="navbar-header">
    <a class="navbar-brand" href="/posts"><div class="numberCircle"><p>BH</p></div></a>
    <p class = "titleHeader">Book Hunt</p>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
    </li>
    <% if user_signed_in? %>
    <li><div class="btn btn-primary" style="color:#fff;margin-top:20px; margin-right:10px;"><%= link_to(current_user.email, destroy_user_session_path, :method => :delete)   %></div>
    </li>
    <% else %>
      <li><div class="btn btn-primary" style="color:#fff;margin-top:20px; margin-right:10px;"><%= link_to "LOGIN",'/users/sign_in' %></div></li>
    <% end %>
    <li><div class="btn btn-primary" style="color:#fff;margin-top:20px; margin-right:10px;"><%= link_to "SUBMIT BOOK",new_post_path %></div></li>
    </ul>
  </div>
</div>

<div class="container">

  <header class="codrops-header">
    <h1> <%= @post.title %> </h1>
  </header>
</div>

<div class="container">
  <header class="codrops-header">
    <h1> <%= @post.content %> </h1>
  </header>
</div>

<div class="container">
  <header class="codrops-header">
    <h1> <%= @post.poster %> </h1>
  </header>
</div>

</script>